project:
  type: website
  output-dir: _site
  
website:
  title: "Vanda Inacio"
  search: false
  navbar: 
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: software.qmd
        text: Software
      - href: teaching.qmd
        text: Teaching 
      - href: miscellanea.qmd
        text: Miscellanea 
      
format:
  html:
    theme: flatly
    css: styles.css
    toc: false

editor: source

